version: '3.8'

services:
  server:
    container_name: fapi_crm
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8008
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
      - ENVIRONMENT=dev
      - TESTING=0
    entrypoint: /start-reload.sh